title: Sunil Tamang
name: Sunil Tamang
email: ""
description: >-
  Outdoor Adventure

# Uncomment when using GitHub Pages
# url: "https://sunil-tamang.github.io"
# baseurl: "/sunil-tamang"

url: "https://tamangsunil.com"
baseurl: ""

# Pretty URLs
permalink: pretty

####################################################
# Collections
####################################################

collections:

  summits:
    output: true
    permalink: /summits/:name/

  films:
    output: true
    permalink: /films/:name/

  team:
    output: true
    permalink: /team/:name/

  services:
    output: true
    permalink: /services/:name/

####################################################
# Default Layouts
####################################################

defaults:

  - scope:
      path: ""
      type: summits
    values:
      layout: summit

  - scope:
      path: ""
      type: films
    values:
      layout: film

  - scope:
      path: ""
      type: team
    values:
      layout: team

  - scope:
      path: ""
      type: services
    values:
      layout: service

####################################################
# Plugins
####################################################

plugins:
  - jekyll-sitemap

####################################################
# Sass
####################################################

sass:
  style: compressed

####################################################
# HTML Compression
####################################################

compress_html:
  clippings: all
  comments: all
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

####################################################
# Strict Front Matter
####################################################

strict_front_matter: true

####################################################
# Excluded Files
####################################################

exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
  - license
  - packages.html
  - "_treks/assets/css/*.scss"